### ISSUE TITLE
Additions to frontend

### ISSUE THREAD

**Issue by asafvala** [idoivri/localbudgets#1]
Advanced search:
1. Add search by name
2. Improve sorting algorithm for table (inside tablesort.js)
3. Add filters after search (for example filter only ארנונה\* after searching everything in year XXXX)

UX:
1. Create a normal page for the advanced search
2. Change normal disclaimer
3. Make contact us button work
4. Search for cool [d3js](http://d3js.org/) visualizations we could add
5. Figure out why you need to click twice for the side-menu to activate
6. Something like [this](http://bl.ocks.org/robschmuecker/7880033) might be nice?
7. Add normal icons to side-menu

**Comment by asafvala** [comment]
Maybe Replace results list with [listjs](http://www.listjs.com/)?

**Comment by nitzanguberman** [comment]
Outdated
