### ISSUE TITLE
Sort values in the pie 

### ISSUE THREAD

**Issue by nitzanguberman** [idoivri/localbudgets#58]
According to their numbers

**Comment by aviillouz** [comment]
- [REFUA_SHLEMA](http://www.jewish-languages.org/jewish-english-lexicon/words/457) to @nitzanguberman 
- ~~Why should we sort ?~~
- ~~we're using d3 partition layout which by default  [sorts values in descending order ](https://github.com/mbostock/d3/wiki/Partition-Layout#sort), so it's already sorted.~~

EDIT: sort by **code** numbers
